
on:
  push:
    branches:
      - main


  pull_request:
    branches:
      - main
  workflow_dispatch:
    
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with: 
        ref: main
    - name: print checked out
      run: echo "checked out to main"